### ISSUE TITLE
timelapse (ffmpeg) requires libomxil-bellagio-dev

### ISSUE THREAD

**Issue by nhandler** [matfra/isitfoggy.today#11]
The timelapse script invokes `ffmpeg`. The flags used require the `libomxil-bellagio-dev` package in order to work. This dependency should be mentioned in README.md

**Comment by matfra** [comment]
Good catch. I knew I was forgetting something !

**Comment by matfra** [comment]
You can now ffmpeg in the official repo and libomxil-bellagio-bin
